# Generated by Django 3.2.12 on 2024-06-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='history',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(default='placeholder_conversation_id', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
